routes:
  - id: users-api
    uri: /users/*
    methods:
      - GET
      - POST
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
    upstream:
      type: roundrobin
      nodes:
        "users-service:8080": 1
